### ISSUE TITLE
numpyro should be lower than v0.13.0, otherwise don't support python 3.8

### ISSUE THREAD

**Issue by LIZW2019** [liuzj039/jpy_tools#1]
Same as title

**Comment by LIZW2019** [comment]
Yes because I found the newest scvi require numpyro, and the update v0.13.0
Drops support for python 3.8 and requires jax version >= 0.4.14

**Comment by liuzj039** [comment]
This repository that doesn't even have unit tests isn't stable enough. You can modify the version as much as you want to make it runnable.
